Allow serde_yaml >= 0.8
Byron/treediff-rs pull request #12
Opened 2023-12-26 16:18 UTC by Yatekii

I think the 0.8 and 0.9 versions do not differ in terms of structures, but 0.9 had the breaking change of requiring tagging. It should be possible to simply support both versions :)

2023-12-26 17:10 UTC, Byron requested changes
Thanks a lot!

Could we play it a bit safer and set an upper bound as well? If 0.9 is considered working, let's add it as bound as well.

Thank you.

2023-12-26 18:25 UTC, Yatekii commented
Sounds good! Also, I realized I was a bit too triggerhappy :( 0.9 added a new variant to the value. Maybe we can add a specific 0.9 feature gate. Would you be happy with that?
I think its a bit ugly but I cant think of a better way :/

2023-12-26 18:42 UTC, Byron commented
Let's make the new minimal version 0.9, and I will create a new breaking release for that. Those who need the latest version of serde-yaml can then use the new major release.

2024-03-27 08:28 UTC, jayvdb commented
Note https://github.com/rustsec/advisory-db/issues/1925

2024-03-27 14:51 UTC, Byron commented
Thanks for the heads-up, I am watching the linked issue now.

2024-03-27 14:56 UTC, Byron commented
Actually this has already been superseded in `main`, as it's using `serde-yaml` 0.9.

2024-03-27 14:56 UTC, closed without merging